version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Tests can run here!"
  deploy:
    machine:
      enabled: true
    steps: 
      - run:
          name: Install mvn & jdk 
          command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt install maven -y && sudo apt install default-jdk
          name: Clone Repo & Install Application Dependencies
          command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/alessiaamele/budget-project && cd ~/budget-project && mvn install"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/budget-project && mvn clean install && mvn spring-boot:run"
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
