version: 2.1
jobs:
  one:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Job One
          command: echo 'This is the first job!'
  two:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Job Two
          command: echo 'This is the second job!
          
  workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - deploy:
          requires:
            - test1
            - test2
            - test3
