workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - deploy:
          requires:
            - test1
            - test2
            - test3
