version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Tests can run here!"
  deploy:
    machine:
      enabled: true
    steps: 
      #- run:
       #   name: Delete previous repo
     #     command: ssh $SSH_USER@$SSH_HOST "rm -r budget-project"
     # - run:
      #    name: Install jdk & maven
      #    command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get install -y git && sudo apt-get install -y openjdk-8-jdk && sudo apt-get install -y maven"
      - run:
           name: Delete Any Old Databases
           command: ssh $SSH_USER@$SSH_HOST "rm -f budget-project.mv.db && rm -r budget-project"
      - run:
          name: Clone Repo
          command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/alessiaamele/budget-project && cd ~/budget-project && mvn install"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/budget-project && mvn clean install && mvn spring-boot:run "
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
